spring:
  application:
    name: onem-backend-kotlin
  profiles:
    active: dev
logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
  file:
    name: "logs/onem-backend-kotlin.log"
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: 10MB
      file-name-pattern: "logs/onem-backend-kotlin-%d{yyyy-MM-dd}.%i.log"
shorten-url:
  expire-minutes: 1
  delete-expired-rate: 30_000 # 30 초 (밀리초 단위)

---

spring:
  config:
    activate:
      on-profile: dev


shortened-url:
  key-prefix: "dev"

---

spring:
  config:
    activate:
      on-profile: stg

shortened-url:
  key-prefix: "stg"

---

spring:
  config:
    activate:
      on-profile: prd

shortened-url:
  key-prefix: "prd"
